export {default as Step1} from "@pages/Auth/ui/AuthSteps/Step1"
export {default as Step2} from "@pages/Auth/ui/AuthSteps/Step2"
export {default as Step3} from "@pages/Auth/ui/AuthSteps/Step3"
export {default as Step4} from "@pages/Auth/ui/AuthSteps/Step4"
export {default as AuthForm} from "./ui/AuthForm/AuthForm"