export const LOGIN_ROUTE = '/login'
export const LOGOUT_ROUTE = '/logout'
export const REFRESH_ROUTE = '/refresh'
export const REGISTRATION_ROUTE = '/registration'
export const DELETE_ACCOUNT_ROUTE = '/delete'
export const FETCH_MESSAGES = '/messages'
export const POST_MESSAGE = '/message'
export const DELETE_MESSAGE = '/message-delete'
