"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FETCH_MESSENGERS = exports.DELETE_ACCOUNT_ROUTE = exports.ACTIVATION_PAGE = exports.REGISTRATION_ROUTE = exports.REFRESH_ROUTE = exports.LOGOUT_ROUTE = exports.LOGIN_ROUTE = void 0;
exports.LOGIN_ROUTE = '/login';
exports.LOGOUT_ROUTE = '/logout';
exports.REFRESH_ROUTE = '/refresh';
exports.REGISTRATION_ROUTE = '/registration';
exports.ACTIVATION_PAGE = '/activate/:link';
exports.DELETE_ACCOUNT_ROUTE = '/delete';
exports.FETCH_MESSENGERS = '/messengers/:user_id';
