"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.POST_MESSAGE = exports.FETCH_MESSAGES = exports.FETCH_MESSENGERS_LIST = exports.FETCH_MESSENGER = exports.DELETE_ACCOUNT_ROUTE = exports.ACTIVATION_PAGE = exports.REGISTRATION_ROUTE = exports.REFRESH_ROUTE = exports.LOGOUT_ROUTE = exports.LOGIN_ROUTE = void 0;
exports.LOGIN_ROUTE = '/login';
exports.LOGOUT_ROUTE = '/logout';
exports.REFRESH_ROUTE = '/refresh';
exports.REGISTRATION_ROUTE = '/registration';
exports.ACTIVATION_PAGE = '/activate/:link';
exports.DELETE_ACCOUNT_ROUTE = '/delete';
exports.FETCH_MESSENGER = '/messenger/:user_id';
exports.FETCH_MESSENGERS_LIST = '/messengers-list/:user_id';
exports.FETCH_MESSAGES = `/messages/`;
exports.POST_MESSAGE = `/message/`;
